In [3]:
import pandas as pd

In [4]:
agent_df=pd.read_csv("artifacts\\agent_roster.csv")
call_logs_df=pd.read_csv("artifacts\\call_logs.csv")
summary_df=pd.read_csv("artifacts\\disposition_summary.csv")

In [5]:
agent_df.head()

  agent_id users_first_name users_last_name users_office_location org_id
0     A001      AgentFirst1      AgentLast1             Bangalore     O1
1     A002      AgentFirst2      AgentLast2                 Delhi     O1
2     A003      AgentFirst3      AgentLast3                Mumbai     O1
3     A004      AgentFirst4      AgentLast4             Bangalore     O3
4     A005      AgentFirst5      AgentLast5             Bangalore     O3

In [6]:
agent_df.isnull().sum()

agent_id                 0
users_first_name         0
users_last_name          0
users_office_location    0
org_id                   0
dtype: int64

In [7]:
call_logs_df.head()

,call_id,agent_id,org_id,installment_id,status,duration,created_ts,call_date
0,C5333,A020,O2,L1826,completed,5.68,2025-04-28T15:40:00,2025-04-28
1,C3045,A018,O1,L1996,no_answer,14.27,2025-04-28T02:41:00,2025-04-28
2,C5803,A018,O1,L1849,failed,11.01,2025-04-28T19:42:00,2025-04-28
3,C2139,A007,O1,L1046,connected,9.02,2025-04-28T09:52:00,2025-04-28
4,C4814,A003,O1,L1887,completed,2.42,2025-04-28T12:58:00,2025-04-28

In [8]:
call_logs_df.isnull().sum()

call_id           0
agent_id          0
org_id            0
installment_id    0
status            0
duration          0
created_ts        0
call_date         0
dtype: int64

In [9]:
summary_df.head()

  agent_id org_id   call_date login_time
0     A001     O1  2025-04-28      11:58
1     A002     O1  2025-04-28      10:05
2     A003     O1  2025-04-28      10:24
3     A004     O3  2025-04-28       8:13
4     A005     O3  2025-04-28        NaN

In [10]:
summary_df.isnull().sum()

agent_id      0
org_id        0
call_date     0
login_time    3
dtype: int64

In [11]:
 # First merge call logs with agent roster
merged_df = pd.merge(
        call_logs_df,
        agent_df,
        on=["agent_id", "org_id"],
        how="left",
        indicator=True
    )

In [12]:
call_logs_df.head()

,call_id,agent_id,org_id,installment_id,status,duration,created_ts,call_date
0,C5333,A020,O2,L1826,completed,5.68,2025-04-28T15:40:00,2025-04-28
1,C3045,A018,O1,L1996,no_answer,14.27,2025-04-28T02:41:00,2025-04-28
2,C5803,A018,O1,L1849,failed,11.01,2025-04-28T19:42:00,2025-04-28
3,C2139,A007,O1,L1046,connected,9.02,2025-04-28T09:52:00,2025-04-28
4,C4814,A003,O1,L1887,completed,2.42,2025-04-28T12:58:00,2025-04-28

In [13]:
agent_df.head()

  agent_id users_first_name users_last_name users_office_location org_id
0     A001      AgentFirst1      AgentLast1             Bangalore     O1
1     A002      AgentFirst2      AgentLast2                 Delhi     O1
2     A003      AgentFirst3      AgentLast3                Mumbai     O1
3     A004      AgentFirst4      AgentLast4             Bangalore     O3
4     A005      AgentFirst5      AgentLast5             Bangalore     O3

In [14]:
merged_df.head()

,call_id,agent_id,org_id,installment_id,status,duration,created_ts,call_date,users_first_name,users_last_name,users_office_location,_merge
0,C5333,A020,O2,L1826,completed,5.68,2025-04-28T15:40:00,2025-04-28,AgentFirst20,AgentLast20,Delhi,both
1,C3045,A018,O1,L1996,no_answer,14.27,2025-04-28T02:41:00,2025-04-28,AgentFirst18,AgentLast18,Bangalore,both
2,C5803,A018,O1,L1849,failed,11.01,2025-04-28T19:42:00,2025-04-28,AgentFirst18,AgentLast18,Bangalore,both
3,C2139,A007,O1,L1046,connected,9.02,2025-04-28T09:52:00,2025-04-28,AgentFirst7,AgentLast7,Bangalore,both
4,C4814,A003,O1,L1887,completed,2.42,2025-04-28T12:58:00,2025-04-28,AgentFirst3,AgentLast3,Mumbai,both

In [15]:
# First merge call logs with agent roster
merged_df = pd.merge(
        call_logs_df,
        agent_df,
        on=["agent_id", "org_id"],
        how="left",
        indicator=True
    )
    
    # Check for unmatched records
unmatched_calls = merged_df[merged_df["_merge"] == "left_only"].shape[0]
if unmatched_calls > 0:
    print("Error")
        
    
    # Remove the indicator column
merged_df = merged_df.drop(columns=["_merge"])
    
    # Now merge with disposition summary
full_merged_df = pd.merge(
        merged_df,
        summary_df,
        on=["agent_id", "org_id", "call_date"],
        how="left",
        indicator=True
    )
    
    # Check for unmatched records after second merge
unmatched_records = full_merged_df[full_merged_df["_merge"] == "left_only"].shape[0]
if unmatched_records > 0:
        print("Error")
    
    # Remove the indicator column
full_merged_df = full_merged_df.drop(columns=["_merge"])

In [16]:
full_merged_df

,call_id,agent_id,org_id,installment_id,status,duration,created_ts,call_date,users_first_name,users_last_name,users_office_location,login_time
0,C5333,A020,O2,L1826,completed,5.68,2025-04-28T15:40:00,2025-04-28,AgentFirst20,AgentLast20,Delhi,9:50
1,C3045,A018,O1,L1996,no_answer,14.27,2025-04-28T02:41:00,2025-04-28,AgentFirst18,AgentLast18,Bangalore,NaN
2,C5803,A018,O1,L1849,failed,11.01,2025-04-28T19:42:00,2025-04-28,AgentFirst18,AgentLast18,Bangalore,NaN
3,C2139,A007,O1,L1046,connected,9.02,2025-04-28T09:52:00,2025-04-28,AgentFirst7,AgentLast7,Bangalore,8:36
4,C4814,A003,O1,L1887,completed,2.42,2025-04-28T12:58:00,2025-04-28,AgentFirst3,AgentLast3,Mumbai,10:24
...,...,...,...,...,...,...,...,...,...,...,...,...
495,C5508,A010,O3,L1062,connected,5.36,2025-04-28T21:22:00,2025-04-28,AgentFirst10,AgentLast10,Mumbai,11:11
496,C9120,A014,O3,L1048,failed,8.80,2025-04-28T21:57:00,2025-04-28,AgentFirst14,AgentLast14,Mumbai,11:05
497,C9592,A013,O1,L1326,no_answer,1.26,2025-04-28T13:56:00,2025-04-28,AgentFirst13,AgentLast13,Delhi,10:01
498,C5913,A005,O3,L1385,connected,14.62,2025-04-28T18:21:00,2025-04-28,AgentFirst5,AgentLast5,Bangalore,NaN
499,C4948,A016,O1,L1869,connected,14.79,2025-04-28T10:15:00,2025-04-28,AgentFirst16,AgentLast16,Delhi,9:05

In [17]:
full_merged_df["presence"] = full_merged_df["login_time"].notna().astype(int)

In [18]:
full_merged_df["login_time"].notna()

0       True
1      False
2      False
3       True
4       True
       ...
495     True
496     True
497     True
498    False
499     True
Name: login_time, Length: 500, dtype: bool

In [19]:
full_merged_df

,call_id,agent_id,org_id,installment_id,status,duration,created_ts,call_date,users_first_name,users_last_name,users_office_location,login_time,presence
0,C5333,A020,O2,L1826,completed,5.68,2025-04-28T15:40:00,2025-04-28,AgentFirst20,AgentLast20,Delhi,9:50,1
1,C3045,A018,O1,L1996,no_answer,14.27,2025-04-28T02:41:00,2025-04-28,AgentFirst18,AgentLast18,Bangalore,NaN,0
2,C5803,A018,O1,L1849,failed,11.01,2025-04-28T19:42:00,2025-04-28,AgentFirst18,AgentLast18,Bangalore,NaN,0
3,C2139,A007,O1,L1046,connected,9.02,2025-04-28T09:52:00,2025-04-28,AgentFirst7,AgentLast7,Bangalore,8:36,1
4,C4814,A003,O1,L1887,completed,2.42,2025-04-28T12:58:00,2025-04-28,AgentFirst3,AgentLast3,Mumbai,10:24,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,C5508,A010,O3,L1062,connected,5.36,2025-04-28T21:22:00,2025-04-28,AgentFirst10,AgentLast10,Mumbai,11:11,1
496,C9120,A014,O3,L1048,failed,8.80,2025-04-28T21:57:00,2025-04-28,AgentFirst14,AgentLast14,Mumbai,11:05,1
497,C9592,A013,O1,L1326,no_answer,1.26,2025-04-28T13:56:00,2025-04-28,AgentFirst13,AgentLast13,Delhi,10:01,1
498,C5913,A005,O3,L1385,connected,14.62,2025-04-28T18:21:00,2025-04-28,AgentFirst5,AgentLast5,Bangalore,NaN,0
499,C4948,A016,O1,L1869,connected,14.79,2025-04-28T10:15:00,2025-04-28,AgentFirst16,AgentLast16,Delhi,9:05,1

In [20]:
 # Convert duration to min
#full_merged_df["duration_minutes"] = full_merged_df["duration"] / 60

In [21]:
# Group by agent, org, and date
performance_df = full_merged_df.groupby(["agent_id", "org_id", "call_date", "users_first_name", "users_last_name", "users_office_location"]).agg(
        total_calls=("call_id", "count"),
        unique_loans=("installment_id", pd.Series.nunique),
        completed_calls=("status", lambda x: (x == "completed").sum()),
        total_duration=("duration", "sum"),
        avg_duration=("duration", "mean"),
        presence=("presence", "max")
    ).reset_index()

In [22]:
performance_df

,agent_id,org_id,call_date,users_first_name,users_last_name,users_office_location,total_calls,unique_loans,completed_calls,total_duration,avg_duration,presence
0,A001,O1,2025-04-28,AgentFirst1,AgentLast1,Bangalore,20,20,2,136.86,6.843000,1
1,A002,O1,2025-04-28,AgentFirst2,AgentLast2,Delhi,23,23,3,180.04,7.827826,1
2,A003,O1,2025-04-28,AgentFirst3,AgentLast3,Mumbai,21,21,8,150.56,7.169524,1
3,A004,O3,2025-04-28,AgentFirst4,AgentLast4,Bangalore,27,27,4,217.53,8.056667,1
4,A005,O3,2025-04-28,AgentFirst5,AgentLast5,Bangalore,29,28,4,204.72,7.059310,0
5,A006,O1,2025-04-28,AgentFirst6,AgentLast6,Chennai,16,16,2,141.40,8.837500,1
6,A007,O1,2025-04-28,AgentFirst7,AgentLast7,Bangalore,24,23,5,168.97,7.040417,1
7,A008,O1,2025-04-28,AgentFirst8,AgentLast8,Mumbai,29,29,8,191.49,6.603103,1
8,A009,O3,2025-04-28,AgentFirst9,AgentLast9,Bangalore,26,25,7,192.07,7.387308,1
9,A010,O3,2025-04-28,AgentFirst10,AgentLast10,Mumbai,38,38,7,307.00,8.078947,1
10,A011,O1,2025-04-28,AgentFirst11,AgentLast11,Chennai,22,22,5,199.47,9.066818,1
11,A012,O3,2025-04-28,AgentFirst12,AgentLast12,Chennai,20,20,5,142.07,7.103500,0
12,A013,O1,2025-04-28,AgentFirst13,AgentLast13,Delhi,22,22,2,151.28,6.876364,1
13,A014,O3,2025-04-28,AgentFirst14,AgentLast14,Mumbai,30,30,10,231.03,7.701000,1
14,A015,O2,2025-04-28,AgentFirst15,AgentLast15,Chennai,28,27,4,238.23,8.508214,1
15,A016,O1,2025-04-28,AgentFirst16,AgentLast16,Delhi,22,22,6,191.44,8.701818,1
16,A017,O2,2025-04-28,AgentFirst17,AgentLast17,Mumbai,20,19,2,133.45,6.672500,1
17,A018,O1,2025-04-28,AgentFirst18,AgentLast18,Bangalore,35,34,6,262.12,7.489143,0
18,A019,O1,2025-04-28,AgentFirst19,AgentLast19,Chennai,27,27,6,186.78,6.917778,1
19,A020,O2,2025-04-28,AgentFirst20,AgentLast20,Delhi,21,21,7,137.82,6.562857,1

In [23]:
 # Calculate connect rate
performance_df["connect_rate"] = (performance_df["completed_calls"] / performance_df["total_calls"])

In [24]:
performance_df

,agent_id,org_id,call_date,users_first_name,users_last_name,users_office_location,total_calls,unique_loans,completed_calls,total_duration,avg_duration,presence,connect_rate
0,A001,O1,2025-04-28,AgentFirst1,AgentLast1,Bangalore,20,20,2,136.86,6.843000,1,0.100000
1,A002,O1,2025-04-28,AgentFirst2,AgentLast2,Delhi,23,23,3,180.04,7.827826,1,0.130435
2,A003,O1,2025-04-28,AgentFirst3,AgentLast3,Mumbai,21,21,8,150.56,7.169524,1,0.380952
3,A004,O3,2025-04-28,AgentFirst4,AgentLast4,Bangalore,27,27,4,217.53,8.056667,1,0.148148
4,A005,O3,2025-04-28,AgentFirst5,AgentLast5,Bangalore,29,28,4,204.72,7.059310,0,0.137931
5,A006,O1,2025-04-28,AgentFirst6,AgentLast6,Chennai,16,16,2,141.40,8.837500,1,0.125000
6,A007,O1,2025-04-28,AgentFirst7,AgentLast7,Bangalore,24,23,5,168.97,7.040417,1,0.208333
7,A008,O1,2025-04-28,AgentFirst8,AgentLast8,Mumbai,29,29,8,191.49,6.603103,1,0.275862
8,A009,O3,2025-04-28,AgentFirst9,AgentLast9,Bangalore,26,25,7,192.07,7.387308,1,0.269231
9,A010,O3,2025-04-28,AgentFirst10,AgentLast10,Mumbai,38,38,7,307.00,8.078947,1,0.184211
10,A011,O1,2025-04-28,AgentFirst11,AgentLast11,Chennai,22,22,5,199.47,9.066818,1,0.227273
11,A012,O3,2025-04-28,AgentFirst12,AgentLast12,Chennai,20,20,5,142.07,7.103500,0,0.250000
12,A013,O1,2025-04-28,AgentFirst13,AgentLast13,Delhi,22,22,2,151.28,6.876364,1,0.090909
13,A014,O3,2025-04-28,AgentFirst14,AgentLast14,Mumbai,30,30,10,231.03,7.701000,1,0.333333
14,A015,O2,2025-04-28,AgentFirst15,AgentLast15,Chennai,28,27,4,238.23,8.508214,1,0.142857
15,A016,O1,2025-04-28,AgentFirst16,AgentLast16,Delhi,22,22,6,191.44,8.701818,1,0.272727
16,A017,O2,2025-04-28,AgentFirst17,AgentLast17,Mumbai,20,19,2,133.45,6.672500,1,0.100000
17,A018,O1,2025-04-28,AgentFirst18,AgentLast18,Bangalore,35,34,6,262.12,7.489143,0,0.171429
18,A019,O1,2025-04-28,AgentFirst19,AgentLast19,Chennai,27,27,6,186.78,6.917778,1,0.222222
19,A020,O2,2025-04-28,AgentFirst20,AgentLast20,Delhi,21,21,7,137.82,6.562857,1,0.333333